- name: print variables from another file
  hosts: local
  connection: local
  vars_files:
  - vars.yaml
  tasks:
  - name: var files
    ansible.builtin.debug:
      msg: "the cousre is {{ COURSE }} and trainer is {{ TRAINER }}"
