- name: filters
  hosts: local
  connection: local
  tasks:
  - name: filters
    ansible.builtin.debug:
      msg: " name is {{ person | default('ramesh') }}"
  - name: convert string to list
    vars:
      fruits: "apple, banana, orange"
    ansible.builtin.debug:
      msg: "fruits are {{ fruits | split(',') }}"
  - name: convert list to map
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'name', 'value': 'sql'}
      - {'key': 'name', 'value': 'jenkins'}
    ansible.builtin.debug:
      msg: "course information: {{ course | items2dict }}"    